"""add evidence bound article handoff

Revision ID: c2047840a2c6
Revises: e6f9a3b21d47
Create Date: 2026-09-22 19:45:13.725493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2047840a2c6'
down_revision: Union[str, Sequence[str], None] = 'e6f9a3b21d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _add_column(table: str, column: sa.Column) -> None:
    if column.name not in {item["name"] for item in sa.inspect(op.get_bind()).get_columns(table)}:
        op.add_column(table, column)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # The initial migration uses Base.metadata.create_all, so fresh databases
    # already receive these tables; existing databases need them added here.
    if not inspector.has_table("mother_revision"):
        op.create_table(
            "mother_revision",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("topic_brief_id", sa.Integer(), nullable=False),
            sa.Column("revision_no", sa.Integer(), nullable=False, server_default="1"),
            sa.Column("title", sa.String(length=500), nullable=True),
            sa.Column("body_markdown", sa.Text(), nullable=False),
            sa.Column("parent_revision_id", sa.Integer(), nullable=True),
            sa.Column("evidence_checksum", sa.String(length=64), nullable=True),
            sa.Column("body_hash", sa.String(length=64), nullable=False),
            sa.Column("import_metadata_json", sa.JSON(), nullable=True),
            sa.Column("created_by", sa.String(length=255), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["topic_brief_id"], ["topic_brief.id"]),
            sa.ForeignKeyConstraint(["parent_revision_id"], ["mother_revision.id"]),
            sa.UniqueConstraint("topic_brief_id", "revision_no", name="uq_mother_revision_topic_no"),
        )
    if not inspector.has_table("draft_media"):
        op.create_table(
            "draft_media",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("draft_id", sa.Integer(), nullable=False),
            sa.Column("content_hash", sa.String(length=64), nullable=False),
            sa.Column("role", sa.String(length=20), nullable=False, server_default="inline"),
            sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("file_path", sa.String(length=500), nullable=True),
            sa.Column("mime_type", sa.String(length=100), nullable=True),
            sa.Column("rights_status", sa.String(length=30), nullable=True),
            sa.Column("public_use_allowed", sa.Boolean(), nullable=True),
            sa.Column("metadata_json", sa.JSON(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["draft_id"], ["draft.id"]),
            sa.UniqueConstraint("draft_id", "content_hash", name="uq_draft_media_hash"),
        )
    if not inspector.has_table("delivery_target"):
        op.create_table(
            "delivery_target",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("content_asset_id", sa.Integer(), nullable=False),
            sa.Column("channel", sa.String(length=30), nullable=False),
            sa.Column("content_form", sa.String(length=30), nullable=False),
            sa.Column("account_ref", sa.String(length=255), nullable=False),
            sa.Column("action", sa.String(length=30), nullable=False, server_default="manual_handoff"),
            sa.Column("authorization_version", sa.String(length=64), nullable=False),
            sa.Column("authorized_by", sa.String(length=255), nullable=True),
            sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("status", sa.String(length=30), nullable=False, server_default="pending"),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["content_asset_id"], ["content_asset.id"]),
            sa.UniqueConstraint("content_asset_id", "channel", "content_form", "account_ref", "authorization_version", name="uq_delivery_target_authorization"),
        )
    if not inspector.has_table("delivery_receipt"):
        op.create_table(
            "delivery_receipt",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("target_id", sa.Integer(), nullable=False),
            sa.Column("status", sa.String(length=30), nullable=False),
            sa.Column("operator", sa.String(length=255), nullable=True),
            sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("evidence_ref", sa.String(length=1000), nullable=True),
            sa.Column("verification_method", sa.String(length=30), nullable=True),
            sa.Column("note", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["target_id"], ["delivery_target.id"]),
        )
    if not inspector.has_table("delivery_feedback"):
        op.create_table(
            "delivery_feedback",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("target_id", sa.Integer(), nullable=False),
            sa.Column("kind", sa.String(length=30), nullable=False, server_default="note"),
            sa.Column("body", sa.Text(), nullable=False),
            sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_by", sa.String(length=255), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["target_id"], ["delivery_target.id"]),
        )
    _add_column('content_asset', sa.Column('approved_candidate_hash', sa.String(length=64), nullable=True))
    _add_column('content_asset', sa.Column('candidate_manifest_json', sa.JSON(), nullable=True))
    _add_column('content_asset', sa.Column('mother_revision_id', sa.Integer(), nullable=True))
    _add_column('draft', sa.Column('mother_revision_id', sa.Integer(), nullable=True))
    _add_column('draft', sa.Column('input_hash', sa.String(length=64), nullable=True))
    _add_column('draft', sa.Column('thread_posts_json', sa.JSON(), nullable=True))
    _add_column('draft', sa.Column('candidate_readiness', sa.String(length=20), nullable=True))
    _add_column('fact_pack_item', sa.Column('evidence_kind', sa.String(length=30), nullable=False, server_default='legacy_untyped'))
    _add_column('fact_pack_item', sa.Column('snapshot_version', sa.Integer(), nullable=True))
    _add_column('fact_pack_item', sa.Column('snapshot_json', sa.JSON(), nullable=True))
    _add_column('fact_pack_item', sa.Column('snapshot_checksum', sa.String(length=64), nullable=True))
    _add_column('fact_pack_item', sa.Column('public_use_allowed', sa.Boolean(), nullable=True))
    _add_column('fact_pack_item', sa.Column('model_use_allowed', sa.Boolean(), nullable=True))
    _add_column('review', sa.Column('candidate_hash', sa.String(length=64), nullable=True))
    _add_column('review', sa.Column('candidate_readiness', sa.String(length=20), nullable=True))
    _add_column('review', sa.Column('warning_dispositions_json', sa.JSON(), nullable=True))
    _add_column('review', sa.Column('checked_input_hash', sa.String(length=64), nullable=True))
    _add_column('review', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # M1 records are audit evidence. Rollback disables entry points rather than
    # deleting versions, approvals, delivery receipts, or related provenance.
    pass
